services:
  - type: web
    name: parkmark-backend
    env: node
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_IOS_CLIENT_ID
        sync: false
      - key: GOOGLE_ANDROID_CLIENT_ID
        sync: false
      - key: APPLE_BUNDLE_ID
        sync: false
      - key: PUSH_API_KEY
        sync: false
